
out: add.o del.o main.o mod.o read.o save.o show.o sort.o 
	cc add.c del.c main.c mod.c read.c save.c show.c sort.c

add.o:add.c
	cc -c add.c
del.o:del.c 
	cc -c del.c
main.o:main.c
	cc -c main.c
mod.o:mod.c
	cc -c mod.c
read.o:read.c
	cc -c read.c
save.o:save.c
	cc -c save.c
show.o:show.c
	cc -c show.c
sort.o:sort.c
	cc -c sort.c

clean:
	rm -f out *.o
